<?xml version="1.0"?>
<robot name="metasejong2025" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_length" value="0.017"/>
  <xacro:property name="base_length" value="0.2"/>
  <xacro:property name="base_width" value="0.2"/>
  <xacro:property name="base_height" value="0.1"/>

  <!-- Base Link -->
  <link name="metasejong2025/base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Left Wheel -->
  <link name="metasejong2025/left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Right Wheel -->
  <link name="metasejong2025/right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Joints -->
  <joint name="metasejong2025/left_wheel_joint" type="continuous">
    <parent link="metasejong2025/base_link"/>
    <child link="metasejong2025/left_wheel"/>
    <origin xyz="0 ${base_width/2} 0" rpy="${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <joint name="metasejong2025/right_wheel_joint" type="continuous">
    <parent link="metasejong2025/base_link"/>
    <child link="metasejong2025/right_wheel"/>
    <origin xyz="0 -${base_width/2} 0" rpy="${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

</robot> 